[workspace.package]
name = "ars_learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "week-one/a-base", "week-one/b-rscli",
]

# [[bin]]
# name = "ws-server"
# path = "projs/web-socket/src/ws_server"


# build release opt
[profile.release]
lto = true
opt-level = 'z'
strip = true
codegen-units = 1
