[package]
name = "btc-payment-grpc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "payment-server"
path = "src/server.rs"
[[bin]]
name = "payment-client"
path = "src/client.rs"

[dependencies]
tonic = "0.11.0"
prost = "0.12.4"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
tonic-build = "0.11.0"
anyhow = "1.0.83"

[build-dependencies]
tonic-build = "0.11.0"