// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Animal {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub age: u32,
    #[prost(oneof = "animal::AnimalType", tags = "3, 4, 5")]
    pub animal_type: ::core::option::Option<animal::AnimalType>,
}
/// Nested message and enum types in `Animal`.
pub mod animal {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum AnimalType {
        #[prost(message, tag = "3")]
        Dog(super::Dog),
        #[prost(message, tag = "4")]
        Cat(super::Cat),
        #[prost(message, tag = "5")]
        Bird(super::Bird),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dog {
    #[prost(string, tag = "1")]
    pub breed: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Cat {
    #[prost(bool, tag = "1")]
    pub has_tail: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Bird {
    #[prost(uint32, tag = "1")]
    pub wingspan: u32,
}
