// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Animal {
    #[prost(string, tag = "1")]
    pub name: String,
    #[prost(uint32, tag = "2")]
    pub age: u32,
    #[prost(enumeration = "AnimalType", tag = "3")]
    pub animal_type: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, prost::Enumeration)]
#[repr(i32)]
pub enum AnimalType {
    Dog = 0,
    Cat = 1,
    Bird = 2,
}
impl AnimalType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            AnimalType::Dog => "DOG",
            AnimalType::Cat => "CAT",
            AnimalType::Bird => "BIRD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> Option<Self> {
        match value {
            "DOG" => Some(Self::Dog),
            "CAT" => Some(Self::Cat),
            "BIRD" => Some(Self::Bird),
            _ => None,
        }
    }
}
