[package]
name = "async-log-watch-a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-log-watch = {version = "0.2"}
async-std = "1.12.0"